# 可以不添加下面4个变量
EXTRA_CFLAGS  := 
CFLAGS_ComFunc.o := 
CFLAGS_uinput_dev.o :=
CFLAGS_uart_to_mcu.o :=
#CFLAGS_queue.o :=


obj-y += ComFunc.o
#obj-y += queue.o
obj-y += uart_to_mcu.o
obj-y += uinput_dev.o
#obj-y += subdir/
